### PR TITLE
fix: better api annotation of valcons matching selection's type

### PR DESCRIPTION
**Pull request by brprice**

### CODE REVIEW

**Comment by brprice** [comment]
This implements https://github.com/hackworthltd/primer/pull/1067#discussion_r1225343753

**Review by georgefst — APPROVED** [review]
Thank you!

**Comment by dhess** [comment]
Thanks! However, keep in mind that what's currently deployed is not `main` but #1070, so maybe add this to that PR so we can get it online and running?

**Comment by dhess** [comment]
I will rebase #1070 when this PR is merged to main, so that we can get this deployed. Thanks all!

**Pull request merged**
