### PR TITLE
feat!: API gives more details on mismatched types

### PR DESCRIPTION
**Pull request by brprice**
For non-empty holes (aka "mismatches"), the OpenAPI now gives both the expected and actual types. We also record the checked-at kind of non-empty type holes in the metadata rather than the synthesised one, for consistency with the term level.

BREAKING CHANGE: this changes the OpenAPI schema.

### CODE REVIEW

**Comment by brprice** [comment]
This PR works pretty well for terms, but for types it is somewhat lacking: in `List {? Maybe ?}` we will report that the mismatch has actual type `* -> *` (good), but say we expect `?` (a kind hole). This makes sense given the kindchecker's behaviour, but we could probably do a better job with the metadata there -- I'll investigate.

We also have a more tricky(?) issue with `{? Nat ?} Bool`, where the mismatch has actual type `*` (good -- this is the kind of `Nat`), and expected type `?` (misleading -- we expected an arrow kind).

**Comment by brprice** [comment]
> This PR works pretty well for terms, but for types it is somewhat lacking: in `List {? Maybe ?}` we will report that the mismatch has actual type `* -> *` (good), but say we expect `?` (a kind hole). This makes sense given the kindchecker's behaviour, but we could probably do a better job with the metadata there -- I'll investigate.
> 
> We also have a more tricky(?) issue with `{? Nat ?} Bool`, where the mismatch has actual type `*` (good -- this is the kind of `Nat`), and expected type `?` (misleading -- we expected an arrow kind).
> 
> Similarly with the term `{? Zero ?} True` we report we expected `?`, but we may prefer to say `? -> ?` (or even `Bool -> ?`, but that is heading to #81 territory)

I've pushed a draft commit that does this for kinds, but not types. The remaining cases to consider are "a term hole in SYN position where the typing rule has a `matchArrow/Forall` constraint" where we could say `? $ True` expects an arrow type, and `? @Bool` expects a forall type. Reporting `? -> ?` and `∀α:?.?` I think is fairly straightforward, but being smarter and constraining those holes is best left to #81.  (Note that this includes saying `? x y` expects type `? -> ? -> ?` rather than just `? -> ?`)

**Comment by brprice** [comment]
On further thought, I have decided to not include any inference/constraint propagation in this PR. Mismatches in synthesisable position which nonetheless have constraints will simply say "expected a hole type", e.g. in `? $ True`, the hole in function position won't say that it requires an arrow type. Further work is left to #81. However we will ensure to treat non-empty type holes in "checkable" position similarly to term holes even though our type level is synthesis-only rather than properly bidirectional.

The reasoning here is 
- let's keep this pr simple so we can merge soon
- further work is lower priority than getting a basic version
- doing better is difficult to do consistently. Consider
  - `{? 1 ?} True`, we could say `expected: ? -> ?`, but why not `Bool -> ?`
  - `? True` should probably have the same "expected" as the non-empty hole version, but this PR is only focusing on displaying the mismatch for non-empty holes
  - `{? 1 ?} True ? Nil` should probably say `Bool -> ? -> List ?` (or maybe `? -> ? -> ?`), but actually reporting this is non-trivial without properly representing and propagating constraints (since this expression is curried, i.e. is actually two nested applications, and thus knowing we need two arrows in the type needs some slightly non-local information)

**Review by georgefst — APPROVED** [review]
Looks good.

This is obviously useful even without (some form of) #81, so I agree with merging in its current state, much as some outputs are unsatisfying.

**Pull request merged**
